### ISSUE TITLE
Fine tuning 

### ISSUE THREAD

**Issue by mzahran001** [gvanhorn38/multibox#2]
How to fine tune your model?
I don't have sufficient data to retrain your model from scratch.
I want to fine tune your model on my data which has only two classes ?

**Comment by gvanhorn38** [comment]
Assuming you have:
- your data in the [correct format](https://github.com/gvanhorn38/inception/tree/master/inputs)
- you have generated your bounding box priors
- you have created a config file for training
- you have downloaded the pretrained [inception-resnet-v3 checkpoint file](https://research.googleblog.com/2016/08/improving-inception-and-image.html)

then the following will train only the detection head layers (the inception-resnet-v3 variables will remain fixed):

``` sh
$ python train.py \
--tfrecords /home/ubuntu/Data/Datasets/COCO/tfrecords/train56945/* \
--priors /home/ubuntu/Data/experiments/detection/large_model_0/priors_7_nonrestricted.pkl \
--logdir /home/ubuntu/Data/experiments/detection/large_model_0/logdir \
--config /home/ubuntu/Data/experiments/detection/large_model_0/config_train.yaml \
--pretrained_model /home/ubuntu/Data/Models/Inception/inception_resnet_v2_2016_08_30.ckpt \
--fine_tune
```

To squeeze more performance out of the detector, you might need to train all of the weights after fine-tuning for a while.
